name: Build - Mac x64

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - v*

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-13
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Fail if branch is not master
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/master'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than master"
          exit 1
      - uses: actions/checkout@v4
      - name: Install OpenSSL
        run: HOMEBREW_NO_INSTALL_CLEANUP=1 brew reinstall openssl@3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: npm install --build-from-source
        env:
          CI: true
          OPENSSL_ROOT_DIR: /usr/local/opt/openssl@3
          OPENSSL_LIBRARIES: /usr/local/opt/openssl@3/lib
      - name: Test
        run: npm run test
        env:
          CI: true
      - name: Upload
        run: node_modules/.bin/prebuild -r napi --upload -u ${{ secrets.GITHUB_TOKEN }}
        env:
          CI: true
